### ISSUE TITLE
Write changelog to a file in the repo

### ISSUE THREAD

**Issue by amitav13** [orhun/git-cliff-action#13]
Hi,
Might be doing something dumb, but - is there no way to write the changelog to a `CHANGELOG.md` within the repo itself? Is that not something that's usual?

Thanks for the action!

**Comment by amitav13** [comment]
Hey no, getting this error:
![CleanShot 2023-12-06 at 19 09 10](https://github.com/orhun/git-cliff-action/assets/7059002/d48a3747-b967-46fe-b5e7-5bb5fc8b3201)

Was getting the same one when I had the `${GITHUB_REPOSITORY}` tag as well.

Here's my action yaml:
```yaml
name: "Tagged release"

on:
  push:
    tags:
      - "[0-9].[0-9].[0-9]*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: --latest --strip header
        env:
          OUTPUT: CHANGELOG.md
      - name: Commit changes to changelog
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "ci: Update changelog"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/Get-Salesmonk/saasmonk-chat.git upstream
```
