### ISSUE TITLE
`config` doesn't seem to work with a subdirectory?

### ISSUE THREAD

**Issue by johnbatclari** [orhun/git-cliff-action#15]
Hi Orhun, thank you for git-cliff-action! It's truly the bees knees! :) 

I think I may have found a quirk with `config`. The following doesn't work as expected:
```yaml
      - name: Update Changelog
        id: changelog
        uses: orhun/git-cliff-action@v2
        with:
          config: config/cliff.toml
          args: --verbose --unreleased --tag ${{ steps.monotag.outputs.tag }} --include-path "${{ inputs.gradle-working-directory }}/**" --include-path "buildSrc/**"
        env:
          OUTPUT: ${{ inputs.gradle-working-directory }}/CHANGELOG.md

```
I get the following:
>  WARN  git_cliff > "cliff.toml" is not found, using the default configuration.

However, passing the config file location in `args` works as expected:
```yaml
      - name: Update Changelog
        id: changelog
        uses: orhun/git-cliff-action@v2
        with:
          args: -c config/cliff.toml --verbose --unreleased --tag ${{ steps.monotag.outputs.tag }} --include-path "${{ inputs.gradle-working-directory }}/**" --include-path "buildSrc/**"
        env:
          OUTPUT: ${{ inputs.gradle-working-directory }}/CHANGELOG.md
```

Not a big deal as there's a clear workaround but thought I'd drop a line here.
