### ISSUE TITLE
Action can't access `github.contributors`; works locally

### ISSUE THREAD

**Issue by welpo** [orhun/git-cliff-action#17]
Hi!

**Short version**: when using the action git-cliff doesn't have access to `github.contributors`. It works locally.

---

I'm using the new GitHub integration (great job!). It works great locally, but when using this action (`orhun/git-cliff-action@main`), I get this in [the logs](https://github.com/welpo/tabi/actions/runs/7964017347/job/21740718279):

```text
+ git-cliff --config=cliff.toml --latest --strip all
 ERROR git_cliff > Template render error:
Variable `github.contributors` not found in context while rendering 'template'
```

My [template](https://github.com/welpo/tabi/blob/0192b3ed9f6df26f28320fd771f445bb74750812/cliff.toml) uses `github.contributors` like this:

```tera
{%- if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 -%}
  {% raw %}\n{% endraw %}### 👥 New contributors
  {% raw -%}\n{% endraw -%}
{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
  🫶 @{{ contributor.username }} made their first contribution
    {%- if contributor.pr_number %} in \
      [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}) \
    {%- endif %}
{% endfor %}
{%- endif %}
```

I understand the issue could be bypassed by adding an extra if like:
```tera
{% if github.contributors %}
{# … the rest of the code above #}
{% endif %}
```

While no errors would be shown in this case, this would skip the contributors section entirely.

I have:
- [X] Set up the `[remote.github]`
- [X] Ran the same command locally; it works fine and grabs the contributor info
- [X] Tried both yesterday after the action update and just a few minutes ago (different repos; same error)
- [X] Provided the env var `GITHUB_TOKEN`. Full [`cd.yml`](https://github.com/welpo/doteki-action/blob/dba23a187f77bd1f101fa856ec329987a69a41f6/.github/workflows/cd.yml):

```yaml
name: Continuous Deployment

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    name: Deploy and release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate the changelog
        uses: orhun/git-cliff-action@main
        id: git-cliff
        with:
          config: cliff.toml
          args: --latest --strip all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT: CHANGES.md

      - name: Create GitHub release
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "${{ steps.git-cliff.outputs.content }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
