### ISSUE TITLE
Make the action faster

### ISSUE THREAD

**Issue by orhun** [orhun/git-cliff-action#18]
Right now we are building the Docker image for the invocation of `git-cliff-action`, see [Docker container action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action) for more information.

It would be nice to use pre-built `git-cliff` binaries instead which would be a huge benefit when it comes to the overall speed of the action.

**Comment by tranzystorekk** [comment]
I could add a manifest for git-cliff to https://github.com/taiki-e/install-action but I'm not sure if we can use it as a dependency here

**Comment by orhun** [comment]
It's a pretty good idea! Let's do that and offer that as an alternative to using this action.

e.g.

```yml
- name: Install git-cliff
  uses: taiki-e/install-action@git-cliff

- name: Generate changelog
  run: git-cliff $args
```

I don't think using that as a dependency here is the way to go.
