### ISSUE TITLE
add hint: --prepend and output is somewhat incompatible

### ISSUE THREAD

**Issue by antonengelhardt** [orhun/git-cliff-action#21]
I had this CI step:

```yaml
- name: Git Cliff
  id: generate_changelog
  uses: orhun/git-cliff-action@v3
  with:
    config: cliff.toml
    args: -l --prepend CHANGELOG.md
  env:
    GITHUB_REPO: ${{ github.repository }}
    OUTPUT: CHANGELOG.md

```

[This is what i have now](https://github.com/antonengelhardt/wasm-oidc-plugin/pull/73/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R30-R37)

My best guess is that the output option replaces the changelog instead of doing the prepend. If that is correct, i would have liked to see a hint that tells me that setting the Output together with `--prepend` as an arg, is not working and one of them should be removed.

Awesome tools though! Cheers
