### ISSUE TITLE
Empty Changelog on github action

### ISSUE THREAD

**Issue by mibelbahri** [orhun/git-cliff-action#42]
Hello team,

I wanted to automate changelog updates with your github action. but this is generating for me an empty changelog:

```
---
name: Update Changelog 🗂️

on:
  pull_request:
    branches:
      - '**'

jobs:
  update-changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          depth: 0
          ref: ${{ github.head_ref }}

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: ./cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"

      - name: Commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -m "doc: update changelog"
          git push
```

Can you please help ?
